#!/bin/bash

export WORK_DIR=~/work
function __goto()
{
	_expath=""
	for var in $@
	do
		_expath="${_expath}${var}.*"
	done
echo  $_expath
	if [ "x${_expath}" == "x" ]
	then
		cd ${WORK_DIR}
		return 0
	fi
	_dir=`ls ${WORK_DIR} | grep "${_expath}"`
	if [ "x${_dir}" == "x" ]
	then
		cd ${WORK_DIR}
		return 0
	fi
	cd ${WORK_DIR}/${_dir}
}
alias wkp='__goto'
function __goto_bak()
{
	_path=$1
	if [ "x${_path}" == "x" ]
	then
		cd ${WORK_DIR}
		return 0
	fi
	_expath=`echo ${_path} | sed 's/./&\\\\{1,\\\\}.*/g'`
	_dir=`ls ${WORK_DIR} | grep ${_expath}`
	if [ "x${_dir}" == "x" ]
	then
		cd ${WORK_DIR}
		return 0
	fi
	cd ${WORK_DIR}/${_dir}
}

alias wk='__goto_bak'

function __goto_dir()
{
	_cd_array=("x." "x.." "x-" "x")
	_cur_dir="."
	_path=$1
	for var in ${_cd_array[@]}
	do
		if [ "x${_path}" == "${var}" ]
		then
			cd ${_path}
			return 0
		fi
	done
	_expath=`echo ${_path} | sed 's/./&\\\\{1,\\\\}.*/g'`
	_dir=`ls ${_cur_dir} | grep ${_expath}`
	if [ "x${_dir}" == "x" ]
	then
		cd ${_cur_dir}
		return 0
	fi
	cd ${_cur_dir}/${_dir}

}
alias cc="__goto_dir"

#repo sync for all
function __reposync()
{
	_currdir=`pwd`
	cd ${WORK_DIR}
	for _dir in `ls | grep "wk_*"`; do
		cd ${WORK_DIR}/${_dir}
		repo sync
		echo ${WORK_DIR}/${_dir}
	done
	cd ${_currdir}
}

alias repoall='__reposync'

