#自动启动nvm, 需要正确安装nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"

# advcpmv should be installed properly
alias cpg='cpg -g'
alias mvg='mvg -g'

# 修改PATH路径,增加home/bin
export PATH="$PATH:$HOME/bin"
