#自动启动nvm, 需要正确安装nvm
#
# export NVM_DIR="$HOME/.nvm" && (
#   git clone https://github.com/creationix/nvm.git "$NVM_DIR"
#   cd "$NVM_DIR"
#   git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`
# ) && . "$NVM_DIR/nvm.sh"
#
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh"  ] && . "$NVM_DIR/nvm.sh"

# advcpmv should be installed properly
# wget http://ftp.gnu.org/gnu/coreutils/coreutils-8.21.tar.xz
# tar xvJf coreutils-8.21.tar.xz
# cd coreutils-8.21/
# wget https://raw.githubusercontent.com/schollz/advcpmv/master/advcpmv-0.5-8.21.patch
# patch -p1 -i advcpmv-0.5-8.21.patch
# ./configure
# make
# sudo mv ./src/cp /usr/local/bin/cpg
# sudo mv ./src/mv /usr/local/bin/mvg
command -v cpg >/dev/null 2>&1 && {
		alias cp='cpg -g'
		alias mv='mvg -g'
	}

# 修改PATH路径,增加home/bin
export PATH="$PATH:$HOME/bin"

# 必须已经安装了perlbrew
# curl -L https://install.perlbrew.pl -o install.perlbrew.pl
# cat install.perlbrew.pl | bash
source ~/perl5/perlbrew/etc/bashrc

# 需要正确安装tmux
#tmux
tmux_init()
{
	tmux new-session -s "work"	 #开启一个会话
	#tmux new-window -n "proj"		#开启一个窗口
	#tmux split-window -h			#开启一个竖屏
	#tmux split-window -v 			#开启一个横屏，并执行top命令
	#tmux -2 attach-session -d		#tmux -2强制启用256color，连接已开启的tmux
}

#判断是否已有开启的tmux会话，没有则开启
if which tmux 2>&1 >/dev/null; then
	test -z "$TMUX" && (tmux attach || tmux_init)
fi
